### ISSUE TITLE
没有看到有适配移动端

### ISSUE THREAD

**Issue by VeigarH5** [lentoo/vue-admin#3]
postcss.cofing.js里面没看到相关的'postcss-px2rem'配置
是不是配置了require('postcss-px2rem')({remUnit: 75, threeVersion: true})后，还需要结合flexible这个适配方案进行移动端适配？

**Comment by lentoo** [comment]
不需要，只需要在main.js 中修改你的设计稿尺寸和rem基数，然后使用rem单位就可以了
